### Tensor Basics

In [1]:
import torch

In [2]:
print(torch.__version__)

1.2.0


In [3]:
torch.cuda.is_available()

False

In [4]:
torch.version.cuda

'10.0'

In [36]:
t = [1,2,3]
t = torch.tensor(t)

In [37]:
type(t)

torch.Tensor

In [38]:
t.shape

torch.Size([3])

In [39]:
t = [[1,2,3],[3,4,5],[5,6,7]]

In [41]:
t = torch.tensor(t)

In [43]:
a = torch.tensor(([1,2,3],[3,4,5],[5,6,7]))

In [44]:
a.shape

torch.Size([3, 3])

In [45]:
a[0]

tensor([1, 2, 3])

In [47]:
a[1][2]

tensor(5)

In [56]:
a = [
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [8,8,8]
]

In [57]:
a = torch.tensor(a)

In [58]:
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [8, 8, 8]])

In [59]:
a.reshape(6,2)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8],
        [9, 8],
        [8, 8]])

In [60]:
import numpy as np 

In [61]:
print(a.dtype)
print(a.device)
print(a.layout)

torch.int64
cpu
torch.strided


In [62]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [63]:
  torch.Tensor(data)

tensor([1., 2., 3.])

In [65]:
torch.tensor(data) ##data type matches input data

tensor([1, 2, 3], dtype=torch.int32)

In [66]:
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [67]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

In [68]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [69]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [70]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [71]:
torch.rand(4,4)

tensor([[0.9186, 0.6569, 0.1486, 0.6594],
        [0.9430, 0.1013, 0.5323, 0.7142],
        [0.4000, 0.3188, 0.1529, 0.2570],
        [0.3321, 0.1528, 0.1200, 0.7683]])

### Create tensors using the 4 options 

In [72]:
data = np.array([1,2,3])

In [75]:
t1 = torch.Tensor(data) #constructor
t2 = torch.tensor(data) # factory fucnction <- returns object (more dynamic object creation)
t3 = torch.as_tensor(data) #factory functions
t4 = torch.from_numpy(data) #fatory function

In [77]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [76]:
print(t1.dtype) #constructor uses global default dtype value
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


In [78]:
torch.get_default_dtype()

torch.float32

#### Factory functions have type inference:

In [80]:
torch.tensor(np.array([1,2,3]))

tensor([1, 2, 3], dtype=torch.int32)

In [81]:
torch.tensor(np.array([1.,2.,3.]))

tensor([1., 2., 3.], dtype=torch.float64)

#### Set data type

In [84]:
torch.tensor(np.array([1,2,3]), dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

#### Constructor and Factory Function Distinct Behavior while modifying array but not tensor


In [101]:
data = np.array([1,2,3])

In [102]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data) #only affects numpy arrays

In [103]:
data[0] = 0
data[1] = 0 
data[2] = 0

`torch.Tensor` and `torch.tensor` contain the original data from the array. Create adittional copy in memory.

In [104]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)


`torch.as_tensor` and `torch.from_numpy` mimic the current array values. Share memory with numpy array.

In [105]:
print(t3)
print(t4)

tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)


*The take away: Use torch.tensor() for everyday use and torch.as_tensor() for performance.
The latters needs to copy numpy array to the GPU.*